# Generated by Django 5.2.17 on 2026-09-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disponibilidade', '0001_initial'),
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidade', to='profissional.profissional'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together={('profissional', 'dia_semana', 'hora_inicio', 'hora_fim')},
        ),
    ]
