# Generated by Django 5.2.17 on 2026-09-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='profissional.profissional'),
        ),
    ]
